### ISSUE TITLE
Code Example of AutoKeras throws a TypeError

### ISSUE THREAD

**Issue by abdulsam** [PracticalDL/Practical-Deep-Learning-Book#126]
If I execute the same code as mentioned in the notebook [https://github.com/PracticalDL/Practical-Deep-Learning-Book/blob/master/code/chapter-5/5-autokeras.ipynb](url), then for the line 
`from autokeras.image.image_supervised import ImageClassifier` , 
it is throwing the following error
**`ModuleNotFoundError: No module named 'autokeras.image'`**

And if I import just 
`from autokeras import ImageClassifier` , 
then while executing the  file, it is throwing an error saying 
**`TypeError: __init__() got an unexpected keyword argument 'path'`** 
on the following part of the code
`clf = ImageClassifier(path=".",verbose=True, augment=True, \
                     searcher_args={'trainer_args':{'max_iter_num':7}}
                                    )`

**Comment by sidgan** [comment]
Thank you for bringing this up. Looks like the AutoKeras package has been updated and its corresponding functions as well. I've added an example code via https://github.com/PracticalDL/Practical-Deep-Learning-Book/pull/128 that works as of June 2020 on a local Ubuntu desktop and on Google Colab. I've also kept the original Oct 2019 code in place as well.
