### ISSUE TITLE
Chapter 3 predictions classifying 'dog' all the time.

### ISSUE THREAD

**Issue by xtr33me** [PracticalDL/Practical-Deep-Learning-Book#132]
I'm trying to figure out why the call to validation_generator.class_indicies is always showing a 1 next to dog. Regardless of whether I use a cat or dog.  Prediction is also showing 2 float values rather than one.  During training, my loss and accuracy are both looking good across the board (approx 97/98%), but when I proceed to test I get results similar to those shown below :

**[[9.9989903e-01 1.0094591e-04]]
{'cat': 0, 'dog': 1}**

I am using Tensorflow-gpu 2.2 under Ubuntu 18.04 Cuda 10.1.  I originally was following with the code in the book, but then verified with your code on git and all seems to look ok to me.  Does anything jump out at you as to what I am doing wrong?

I have attached a screenshot showing the test result.
<a href="https://ibb.co/grKs0D2"><img src="https://i.ibb.co/S6CqkKj/DL-Cat-Dog-Screenshot.png" alt="DL-Cat-Dog-Screenshot" border="0"></a>

**Comment by sidgan** [comment]
The `validation_generator.class_indices` prints out the index of each class in the dataset, so it's always going to show cat as 0 and dog as 1, irrespective of the input image. 

If we look at the values printed out by `prediction` we see that cat has a higher probability (10-1) vs dog at 10-5 which is in line with the input image of `cat.jpg`

**Comment by xtr33me** [comment]
Thank you sidgan!  I've been trying to figure this out for the past couple days lol.  Thought that the 1 represented which it was inferring, but I did notice the probabilities seemed correct.  Thank you and sorry for wasting your time.

**Comment by sidgan** [comment]
No worries! Cell 11 and 12 may be relevant to print out accuracy and class indexes for the correct predictions: [chapter-3/2-analyzing-the-results.ipynb](https://github.com/PracticalDL/Practical-Deep-Learning-Book/blob/master/code/chapter-3/2-analyzing-the-results.ipynb)
