### ISSUE TITLE
The gzip file cannot be unzipped

### ISSUE THREAD

**Issue by ShubhamGupta19** [PracticalDL/Practical-Deep-Learning-Book#138]
![Firefox_Screenshot_2020-09-21T20-51-20 996Z](https://user-images.githubusercontent.com/42578435/93820133-545fde00-fc7a-11ea-8eb8-3cf9ffbd0fc9.png)

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

I tried all the ways but its not getting unzipped

**Comment by sidgan** [comment]
Looks like the [Caltech 101 dataset](http://www.vision.caltech.edu/Image_Datasets/Caltech101/#Download) has moved locations and now has to be downloaded through the [Google Drive](https://drive.google.com/file/d/137RyRjvTBkBiIfeYBNZBtViDHQ6_Ewsp) link. I've updated the code to use `gdown` to download the dataset. Thanks for reporting!
