### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by leminhds** [PracticalDL/Practical-Deep-Learning-Book#149]
please add back the requirements.txt the various package used here have many conflicts if we just update to the latest version. I am having a lot of difficulty setting up to start working in chapter 5 for example

**Comment by sidgan** [comment]
Thank you for your comments. Consider using the colab ready environments as they are easier to use. 

- For `1-develop-tool.ipynb`, two small changes have been added: (1) upgrade to `tensorflow-gpu==2.5.0` and (2) replace image import as `import tensorflow.keras.preprocessing.image` 
- I've deprecated `gradcam-tf-explain-catdog.ipynb` in Chapter-5, and instead please run `2-colab-what-does-my-neural-network-think.ipynb`
- For `autokeras.ipynb`, upgrades to packages include: `tensorflow-gpu==2.5.0, keras-tuner --upgrade`

Other notebooks work fine on my end.

**Comment by sidgan** [comment]
Hi @leminhds  I've updated the notebooks to include the install versions in the first few cells. Please try it out.
