### ISSUE TITLE
Invalid Argument Error

### ISSUE THREAD

**Issue by PriyankaJain-1998** [PracticalDL/Practical-Deep-Learning-Book#150]
![image](https://user-images.githubusercontent.com/58905207/125260435-f510ae80-e31d-11eb-85dc-551bb7c480a3.png)
![image](https://user-images.githubusercontent.com/58905207/125260490-fe018000-e31d-11eb-8a1c-a1d399d7a25d.png)
whille training or running this particular code snippet, showing this error. 
Please help me out.

**Comment by sidgan** [comment]
Please clarify which notebook is this?

**Comment by Woingenau** [comment]
I had the same Problem, i guess that you have more than 2 classes that you want a prediction for.
You need to change the NUM_CLASSES in the beginning to the number of outputs you want to have.

**Comment by sidgan** [comment]
Hi @PriyankaJain-1998  and @Woingenau thank you for sharing details in this issue. Which exact notebook is this? I'll be able to better help if I'm able to replicate the issue :)

**Comment by PriyankaJain-1998** [comment]
Hi @sidgan this is under chapter 4 notebook.

**Comment by sidgan** [comment]
Hi @PriyankaJain-1998 , I'm not able to replicate the exact same issue you posted but looks like there are some updates to Keras generators that do not require one to specify `batch_size` and I've reflected that and made necessary adjustments in the [chapter-4/1-feature-extraction.ipynb](https://github.com/PracticalDL/Practical-Deep-Learning-Book/blob/master/code/chapter-4/1-feature-extraction.ipynb) notebook via https://github.com/PracticalDL/Practical-Deep-Learning-Book/pull/155

**Comment by sidgan** [comment]
Added via https://github.com/PracticalDL/Practical-Deep-Learning-Book/pull/155
