### ISSUE TITLE
chapter-4/1_feature_extraction.ipynb finetuned model was predicting 101 classes and not 2048 features

### ISSUE THREAD

**Issue by gitgithan** [PracticalDL/Practical-Deep-Learning-Book#168]
The finetuned model generated 101 columns. 
It should have been truncated at the end to only predict on the feature extraction layers to produce a 2048 dimension vector per image, which makes it consistent with the model before finetuning. 

All subsequent notebooks have drastically different accuracy results maybe due to this issue

**Comment by koul** [comment]
Hi @gitgithan , appreciate leaving all the great feedback.

**Comment by koul** [comment]
We'll be looking to improve into this in some time.
