### ISSUE TITLE
No Chapter 9 code

### ISSUE THREAD

**Issue by grewe** [PracticalDL/Practical-Deep-Learning-Book#21]
There is no chapter 9 code...what h5_to_tf.ipynb that is supposed to be in this repository under chapter-9 directory

**Comment by sidgan** [comment]
Hi @grewe, thank you for pointing it out. We are uploading the code chapter by chapter and just updated [chapter-9](https://github.com/PracticalDL/Practical-Deep-Learning-Book/tree/master/code/chapter-9).
