### ISSUE TITLE
Benchmarking on chapter4

### ISSUE THREAD

**Issue by jhagege** [PracticalDL/Practical-Deep-Learning-Book#42]
Hi,
In the notebook 2-similarity-search-level-2.ipynb, would you recommend running on a subset of the features / classnames / filenames ? 
The benchmarks takes a very long time, maybe it would be better to add some code to select a subpart of the files only.

**Comment by sidgan** [comment]
For ease of illustration and speed, you can pick a few images as follows:

selected_features = feature_list[7000:8000]
selected_class_ids = class_ids[7000:8000]
selected_filenames = filenames[7000:8000]

This is demonstrated in [`chapter-4/2-similarity-search-level-1.ipynb`](https://github.com/PracticalDL/Practical-Deep-Learning-Book/blob/master/code/chapter-4/2-similarity-search-level-1.ipynb).

Remember that it is important to run the entire dataset if you wish to benchmark the entire dataset.

**Comment by jhagege** [comment]
Great, I realized later it took a long time because I forgot to add the pooling='max' to the network architecture, therefore having about 100k features instead of 2048.
Thanks much though :)
