### ISSUE TITLE
AnnoyIndex - Vector has wrong length

### ISSUE THREAD

**Issue by jhagege** [PracticalDL/Practical-Deep-Learning-Book#43]
When trying to run the AnnoyIndex code of 2-similarity-search-level-2, I get the following error: 

> IndexError: Vector has wrong length (expected 2048, got 500)

Should the length of features passed be 2048 ?

**Comment by jhagege** [comment]
(the original number of features per image is 100352)

**Comment by jhagege** [comment]
I think I found the issue. 
The feature extractor didn't have the pooling='max' parameter in resnet50. 
Added it, and now getting features of length 2048 :)

**Comment by sidgan** [comment]
Can you please clarify which `AnnoyIndex` section you are referring to.

**Comment by jhagege** [comment]
> I think I found the issue.
> The feature extractor didn't have the pooling='max' parameter in resnet50.
> Added it, and now getting features of length 2048 :)

Actually issue is not relevant anymore ,since root cause was this. 
Thanks for your quick answer.
