### ISSUE TITLE
CLASS_INDEX_PATH should take URL instead of relative path

### ISSUE THREAD

**Issue by ganmohim** [PracticalDL/Practical-Deep-Learning-Book#58]
**Issue**

https://github.com/PracticalDL/Practical-Deep-Learning-Book/blob/master/code/chapter-2/visualization.py

Run the following command to run the program:
`python visualization.py --process image --path ../../sample-images/dog.jpg`

The program will fail if you are running this locally (not on Colab) for the first time:
```
data_utils.py", line 251, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 510, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.7/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.7/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.7/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '../imagenet_class_index.json'


```

**Code**
https://github.com/PracticalDL/Practical-Deep-Learning-Book/blob/master/code/chapter-2/visualization.py

```
CLASS_INDEX_PATH = '../imagenet_class_index.json'
...
 if CLASS_INDEX is None:
        fpath = get_file('imagenet_class_index.json',
                         CLASS_INDEX_PATH, cache_subdir='models')
        CLASS_INDEX = json.load(open(fpath))
```

**Issue**
TensorFlow's `get_file()` API lists the second parameter as URL not as relative path: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/utils/data_utils.py#L164

Under the hood, it uses following code:
```
try:
        urlretrieve(origin, fpath, dl_progress)
      except HTTPError as e:
        raise Exception(error_msg.format(origin, e.code, e.msg))
```

The following one-liner will fix the issue:
`CLASS_INDEX_PATH = 'https://s3.amazonaws.com/deep-learning-models/image-models/imagenet_class_index.json'`

**Note**
1) If someone runs this example once using the one-liner fix, the current code as is would work because it uses cached data `imagenet_class_index.json`. Probably that is how the bug snuck in.

2) Easy fix, but I could not make pull request due to permission. You can technically enable PR by protecting your branch. This way any merge will be blocked until code owners approve the PR. This will help you to keep the code up-to-date by leveraging external PR. Just food for thought.

**Comment by meherkasam** [comment]
Thank you for your detailed message, Gan. It does sound like an oversight on my end. I've changed the master branch protection rule, so can you now try to create a pull request? If it doesn't work, I'll be happy to do the fix.

**Comment by ganmohim** [comment]
Sure. I will make a PR. Thanks @meherkasam.
