### ISSUE TITLE
Input format on tf_explain for ExtractActivations

### ISSUE THREAD

**Issue by elviejokike** [PracticalDL/Practical-Deep-Learning-Book#59]
The data passes to the explain method (when using ExtractActivations) must be fixed to 

    data_for_activation = (np.array([img]), None)
    grid = explainer.explain(data_for_activation, model, ['conv1'])

https://github.com/PracticalDL/Practical-Deep-Learning-Book/blob/master/code/chapter-5/3-tf-explain.ipynb

**Comment by sidgan** [comment]
Thank you for pointing out the error. Fixed via https://github.com/PracticalDL/Practical-Deep-Learning-Book/pull/62
