### ISSUE TITLE
Predict chapter 2

### ISSUE THREAD

**Issue by chris-kehl** [PracticalDL/Practical-Deep-Learning-Book#87]
chapter 2 shows the dog with code
predict(img)

the github code doesn't include this line, but if we implement the code the following error is received.

NameError: name 'predict' is not defined

**Comment by sidgan** [comment]
Thank you for pointing this out, Chris! 

Looks like you are referring to Figure 2-3 with the `predict(img)` code. A similar function has been used in this notebook https://github.com/PracticalDL/Practical-Deep-Learning-Book/blob/master/code/chapter-2/1-predict-class.ipynb but had been originally named `classify()`. 

I've updated it to `predict()` via https://github.com/PracticalDL/Practical-Deep-Learning-Book/pull/88

**Comment by chris-kehl** [comment]
Great,  thank you!  Working through the chapters.  Learning a lot.

Thanks for writing the book.

Chris Kehl

**Comment by sidgan** [comment]
Appreciate it! Glad you are finding the book useful!
