### ISSUE TITLE
Ch5-1-develop-tool.ipynb notebook throws error when running get_dataset() method

### ISSUE THREAD

**Issue by ManojKumarTiwari** [PracticalDL/Practical-Deep-Learning-Book#93]
I have not made any changes to the code but when I run the below code

train, info_train, val, info_val, IMG_H, IMG_W, IMG_CHANNELS, NUM_CLASSES, NUM_EXAMPLES = get_dataset(dataset_name, 100)

I am getting an error saying
AssertionError: Unrecognized instruction format: NamedSplit('train')(tfds.percent[0:90])

Please help. Thank You

**Comment by meherkasam** [comment]
Thanks for reporting this issue. It looks like the API we were using has been deprecated by the TensorFlow team. I've updated the code to use the new API and have attached the pull request here.

**Comment by meherkasam** [comment]
I've merged to master. Please try it now.
