### ISSUE TITLE
Ch-6 Store as TF Records 

### ISSUE THREAD

**Issue by vishwanath79** [PracticalDL/Practical-Deep-Learning-Book#95]
For example on creating TFRecords - Consider adding the following functions to store the packed BytesList and Int64List as per the documentation to assist the reader, throws an error otherwise.

    def _int64_feature(value):
      return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

    def _bytes_feature(value):
      return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

**Comment by sidgan** [comment]
Thank you for bringing this up. Addressed via https://github.com/PracticalDL/Practical-Deep-Learning-Book/pull/105.
